server.port: 8081

spring:
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/albums?useSSL=false
    username: root

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG

s3:
  accessKey: AKIAJ4MFRP36JV26WZPA
  secretKey: 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
  bucketName: cf-0a05c016-b498-4ee4-95e8-9f40ceb861e2
  endpointUrl: http://cf-0a05c016-b498-4ee4-95e8-9f40ceb861e2.s3.amazonaws.com
security:
  basic:
    enabled: false
